cartoonapp/urls.py
from . import views
from django.contrib import admin
from django.urls import path
app_name='cartoonapp'



urlpatterns = [
    path('',views.index, name='index'),
    path('cartoon/<int:cartoon_id>/',views.detail,name='detail'),
    path('add/',views.add_cartoon,name='add_cartoon'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

cartoonproject/urls.py
from xml.etree.ElementInclude import include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("cartoonapp.urls"))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cartoonapp/models.py
from django.db import models

# Create your models here.

class Cartoon(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pictures')


    def __str__(self):
        return self.name

cartoonapp/forms.py
from django import forms
from .models import Cartoon


class CartoonForm(forms.ModelForm):
    class Meta:
        model=Cartoon
        fields=['name','desc','year','img']

cartoonapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Cartoon
from .forms import CartoonForm

# Create your views here.


def index(request):
    cartoon=Cartoon.objects.all()
    context={'cartoon_list':cartoon}

    return render(request,"index.html",context)


def detail(request,cartoon_id):
    cartoon=Cartoon.objects.get(id=cartoon_id)
    return render(request,"detail.html",{'x':cartoon})

def add_cartoon(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        cartoon=Cartoon(name=name,desc=desc,year=year,img=img)
        cartoon.save()
    return  render(request,"add.html")


def update(request,id):
    cartoon=Cartoon.objects.get(id=id)
    form=CartoonForm(request.POST or None,request.FILES,instance=cartoon)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'cartoon':cartoon})


def delete(request,id):
    if request.method=='POST':
        cartoon=Cartoon.objects.get(id=id)
        cartoon.delete()
        return redirect('/')

    return render(request,'delete.html')

templates/add.html
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <input type="text" name="name" placeholder="enter your cartoon name ">
  <input type="text" name="desc" placeholder="enter the cartoon description">
  <input type="text"name="year" placeholder="enter cartoor year">
  <input type="file" name="img">
  <input type="submit">

{% endblock %}



</form>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Cartoon Store
  </a>
    <a href="{% url 'cartoonapp:add_cartoon' %}" class="btn btn-primary">Add Cartoon</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">

    {% csrf_token %}
    Are you sure want to delete this cartoon?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-5">
          <img src="{{x.img.url}}" width="300" height="300">
        </div>

        <div class="col-md-5">

            <h3>{{x.name}}</h3>
            <h6>{{x.year}}</h6><br>
            <h6>{{x.desc}}</h6><br>
            <a class="btn btn-warning" href="{% url 'cartoonapp:update' x.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'cartoonapp:delete' x.id %}">Delete</a>
        </div>
    </div>
</div>



{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit">



</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in cartoon_list %}

        <div class="col-md-4" style="padding:20px;">

            <div class="card" style="width:15rem;height:25rem">
            <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>

                <a href="{%url 'cartoonapp:detail' i.id %}" class="btn btn-primary">More Details</a>
            </div>
            </div>


        </div>
        {% endfor %}
    </div>

</div>


{% endblock %}